# Use an official OpenJDK runtime as a parent image
FROM openjdk:8-jre-slim

# Set the working directory within the container
WORKDIR /app

# Copy the JAR file from your project's directory to the container
COPY target/BookStoresProject.jar /app/BookStoresProject.jar

# Expose the port your Spring Boot application will run on (adjust as needed)
EXPOSE 8089

# Define the command to run your application
CMD ["java", "-jar", "BookStoresProject.jar"]
